"""Push hf_data_staging/ to the anonymous-review HuggingFace dataset repo as a PR.

Default behavior is **additive**: uploads files in the local staging dir and
leaves anything else on HF untouched. Use this for adding new runs over time.

For explicit deletion, pass --delete <pattern> (repeatable). Patterns are
glob-style relative to the repo root, e.g.:

    --delete "core_evaluator_capture/**"
    --delete "core_privacy/llm/claude-opus-4-6/**"

The push opens a draft PR on HF, not a direct push to main.

Pre-flight: requires HF_TOKEN with write scope on anon-author-B41C/evaluation-ecosystem-data.

Workflow:
  1. python scripts/run_experiment.py --no-dev --bucket <X> ...   # produce runs into staging
  2. python scripts/slim_heuristic_runs.py                        # slim heuristic runs in place (no-op if no heuristics)
  3. python scripts/build_hf_metadata.py                          # regenerate runs.jsonl + README + manifest
  4. python scripts/push_hf_data.py --dry-run                     # sanity check
     python scripts/push_hf_data.py                               # additive push
     python scripts/push_hf_data.py --delete "<pattern>"          # additive + selective delete

Usage:
  python scripts/push_hf_data.py --dry-run                        show what would happen
  python scripts/push_hf_data.py                                  additive push (default)
  python scripts/push_hf_data.py --delete "path/**"               include explicit deletions
  python scripts/push_hf_data.py --replace-all                    nuclear: wipe HF, replace from staging
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parent.parent
STAGING = PROJECT_ROOT / "hf_data_staging"
HF_REPO_ID = "anon-author-B41C/evaluation-ecosystem-data"

DEFAULT_COMMIT_MESSAGE = "Update dataset"
DEFAULT_COMMIT_DESCRIPTION = """\
Additive sync of hf_data_staging/ from the simulation repo.

New or changed files are uploaded; files already present on HF that are not in
the staging dir are left untouched (unless --delete patterns were specified).

Top-level files (`README.md`, `DATASHEET.md`, `manifest.json`, `runs.jsonl`)
are regenerated by `scripts/build_hf_metadata.py` before each push and reflect
the current staging contents.
"""


def file_count_and_size(root: Path) -> tuple[int, int]:
    count = 0
    size = 0
    for p in root.rglob("*"):
        if p.is_file():
            count += 1
            size += p.stat().st_size
    return count, size


def fmt_bytes(n: float) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024:
            return f"{n:.1f}{unit}"
        n /= 1024
    return f"{n:.1f}TB"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dry-run", action="store_true",
                    help="Print what would be uploaded; do not contact HuggingFace.")
    ap.add_argument("--repo-id", default=HF_REPO_ID,
                    help=f"HuggingFace dataset repo id (default: {HF_REPO_ID})")
    ap.add_argument("--commit-message", default=DEFAULT_COMMIT_MESSAGE,
                    help="PR title.")
    ap.add_argument("--commit-description", default=DEFAULT_COMMIT_DESCRIPTION,
                    help="PR body.")
    ap.add_argument("--delete", action="append", default=[],
                    metavar="PATTERN",
                    help="Glob pattern (repo-relative) of paths to delete on HF. "
                         "Repeatable. Files matching are removed from the repo as part of "
                         "the same commit. Example: --delete 'case_studies/**' "
                         "--delete 'core_privacy/llm/claude-opus-4-6/**'")
    ap.add_argument("--replace-all", action="store_true",
                    help="DESTRUCTIVE: replace all repo content with the local staging dir "
                         "(equivalent to --delete '*'). Use only for full resets.")
    args = ap.parse_args()

    if not STAGING.is_dir():
        print(f"ERROR: {STAGING} does not exist.", file=sys.stderr)
        return 1

    delete_patterns = list(args.delete)
    if args.replace_all:
        delete_patterns = ["*"]

    n_files, n_bytes = file_count_and_size(STAGING)
    print(f"Staging: {STAGING.relative_to(PROJECT_ROOT)}")
    print(f"  {n_files} files, {fmt_bytes(n_bytes)}")
    print(f"Target:  https://huggingface.co/datasets/{args.repo_id}")
    if delete_patterns:
        print(f"Mode:    additive + delete patterns:")
        for p in delete_patterns:
            print(f"           {p!r}")
    else:
        print("Mode:    additive (no deletions)")
    print(f"PR title: {args.commit_message}")

    if args.dry_run:
        print("\nDry-run: not contacting HuggingFace.")
        return 0

    load_dotenv(PROJECT_ROOT / ".env")
    token = os.environ.get("HF_TOKEN")
    if not token:
        print("ERROR: HF_TOKEN not found in .env. Need write scope on the dataset repo.",
              file=sys.stderr)
        return 1

    from huggingface_hub import HfApi

    api = HfApi(token=token)
    print("\nUploading and opening PR ...")
    upload_kwargs = dict(
        folder_path=str(STAGING),
        repo_id=args.repo_id,
        repo_type="dataset",
        create_pr=True,
        commit_message=args.commit_message,
        commit_description=args.commit_description,
    )
    if delete_patterns:
        upload_kwargs["delete_patterns"] = delete_patterns
    commit_info = api.upload_folder(**upload_kwargs)
    print(f"PR opened: {commit_info.pr_url}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
